### ISSUE TITLE
Some addresses get geocoded by Census Website but not De-Gauss

### ISSUE THREAD

**Issue by sneharav15** [degauss-org/geocoder#33]
Hello! I see that there are addresses that get geocoded by the census geocoder tool (https://geocoding.geo.census.gov/geocoder/) but not by de-gauss. I was just wondering why this might be the case? Are there some differences in the matching algorithm or in the TIGER database? I am happy to send over some examples via email if that will be helpful. Thanks!

Sneha

**Comment by cole-brokamp** [comment]
Yes, I would assume that there are a lot of differences between DeGAUSS and the census geocoder.  The TIGER database should be the same if from the same year since we get it directly from the census, but the methodology of the census geocoder is unclear (or I couldn't find it easily...)

In general, most geocoders will not produce exactly the same results given the same address.  Some won't even produce the same results over time either!

**Comment by sneharav15** [comment]
Hi Cole, thanks for your reply! Just following up to see if you can provide a little more detail on this - I would like to get a better understanding of this issue.

1) If the same TIGER 2021 database is used by both Census and De-Gauss, why does this difference exist?
2) What is the methodology used by De-Gauss? Is there a place where I can see the implementation steps?
3) I am not sure I understand why geocoders will not produce the same results given the same address or even over time? Would you be able to elaborate more on this?

Thank you!
