### ISSUE TITLE
geocoder 3.2.1 crash

### ISSUE THREAD

**Issue by maurosc3ner** [degauss-org/geocoder#41]
Hi, 

I am using degauss for geocoding addresses at Cincinnati. If the CSV file surpasses 500k rows, it crash after +3 hrs of geocoding. I can avoid this crash by splitting the file in R and calling the geocoder from a bash file but I guess there is something else. Please find attached the backtrace from the terminal:

OS: Mac OS Big Sur 

<img width="644" alt="Screen Shot 2022-08-16 at 2 57 25 PM" src="https://user-images.githubusercontent.com/4038971/184959654-3b817466-3679-4f70-841b-0fbf4b507395.png">

Thanks,

**Comment by maurosc3ner** [comment]
Hi Cole,

I usually use the last version available in the degauss site, but when I keep having errors I also use 3.0.2. The command used for both full and chunk-like files was:

`docker run --rm -v $PWD:/tmp ghcr.io/degauss-org/geocoder:3.2.1 file.csv`

Thanks,
Esteban

**Comment by cole-brokamp** [comment]
Hmm, what makes you say over 500k rows?  Is that an estimate or is it something about that exact number?

After you split the problematic file, are both halves able to be geocoded without error?

**Comment by cole-brokamp** [comment]
That helps a lot -- so it seems to definitely be a limitation of the _number_ of addresses, not necessarily something in the address data itself.

I'm wondering if it just crashes because the docker container doesn't have enough RAM.  Since it uses R under the hood, the input data is completely read into memory and would crash for larger datasets. We've definitely used it on millions of rows at a time without problems before, but this was on an instance where we had hundreds of GB of RAM available to the process.  

If you are running in Docker Desktop, could you try increasing the amount of system RAM available for Docker to use?  Otherwise, sharding data for use through DeGAUSS and combining after geocoding might be the only way to get it through.
