### ISSUE TITLE
Geocoding does not work when reading in the file with addresses

### ISSUE THREAD

**Issue by helpWithCoding** [degauss-org/geocoder#46]
Hi, I am trying to use your tool for geocoding while complying with PHI and am unable to proceed after DeGAUSS Geocoder reads the file. I get a similar error as this in your troubleshooting guide (https://degauss.org/troubleshooting.html#Parallel_Computing_on_Windows). 

My error is the following: 
`Error in fifo(tempfile(), open = "w+b", blocking = T) :
  cannot open the connection
Calls: <Anonymous> -> mclapply_pb -> fifo
In addition: Warning message:
In fifo(tempfile(), open = "w+b", blocking = T) :
  cannot create fifo '/tmp/RtmpyawNEg/file128e110e', reason 'Operation not supported'
Execution halted`

I tried as suggested to set the .wslconfig processors to 1 and still did not work. I did see an earlier suggestion to set RAM to 4GB and processes to 2 and was not working either. I removed the memory line and left processses = 1 and still nothing.

This is my current .wslconfig file:

[wsl2]
kernel=C:\\temp\\myCustomKernel
processors=1 # Makes the WSL 2 VM use one virtual processors

I am using windows 11. 

Any advice on getting this to work is greatly appreciated. I have made sure that docker and linux subsystem (Ubuntu in this case) is shut down before trying again to no avail. 

I also used this guide to set the limits (only for RAM and processes) but it did not work: https://mrakelinggar.medium.com/set-up-configs-like-memory-limits-in-docker-for-windows-and-wsl2-80689997309c

**Comment by cole-brokamp** [comment]
Hi, thanks for the details.  We have not tested DeGAUSS extensively, or really at all, on WSL. Are you able to run the example in the readme using the test file included in the repository?

**Comment by helpWithCoding** [comment]
thanks for getting back to me regarding my question, I really need your help as my graduation from my MPH in epidemiology and biostatistics and thesis depend on getting DeGAUSS Geocoding to work, I was able to get it to work using powershell, however, I got a lot of NAs after running DeGAUSS Geodcoding

**Comment by helpWithCoding** [comment]
do you have any advice for this?

**Comment by cole-brokamp** [comment]
I would find a way to use powershell or try to run the example to make sure that it is something now with your specific data.  Please see below for how to create an example that we can use to help troubleshoot your issue:


Thanks for your message!  In order for us to best help you, please create a [minimal reproducible example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example) of the error, bug, or issue that you are encountering.

An MRE is intended to reproduce an error using the smallest amount of code, which will save troubleshooting time and effort. It also ensures that the problem is related to code in this repository, as opposed to other software tools being used alongside DeGAUSS or to your specific input data.  Once we can reproduce the specific problem, then we can work to troubleshoot it.

DeGAUSS is often used with sensitive and private data that cannot be shared, so using a contrived, random, or simulated example dataset might be necessary.  Every DeGAUSS repository has [test](https://github.com/degauss-org/geocoder/blob/master/test/my_address_file.csv) [input](https://github.com/degauss-org/census_block_group/blob/master/test/my_address_file_geocoded.csv) files that are useful for troubleshooting and trying to create a MRE.
