### ISSUE TITLE
3.0 release

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/geocoder#6]
roadmap for 3.0 release:
- [x] update geocoder database file with the 2019 TIGER/Line files (`s3://geomarker/geocoder-2019.db`)
- [x] add Makefile and testing directory
- [x] force column name as `address` rather than taking as an input
- [x] create column called "geocode_result" with possible values of: cincy_inst_foster_addr, po_box, non_address_text, geocoded, imprecise_match (not range or street and/or score < 0.5)
     - summarize these results in a user message
     - add hidden option to change threshold from 0.5
     - make sure to return diagnostic / matched columns with "matched_" prepended
- [x] use cli package for better messages (use dht helper package?)
- [x] embed version number in geocoding output filename
- [x] use renv for package management
- [x] pull in preprocessing of text things from cchmc_batch_geocoder (except for tract fips stuff)
   - [x] fix dash removal
   - [x] move removing whitespace down stringr::str_squish
   - [x] check for any blank addresses to remove ahead of time (including after removal of non-alphanumeric characters)
- [x] README updates
    - [x] update to take form of template/dht
    - [x] move all "manual installation" instructions to the wiki
    - [x] make sure that degauss.org instructions are up to date with new release
    - [x] announce now using 2019 T/L files; add note about versioning
    - [x] mention can take other data in CSV, but not recommended

should we deprecate the batch geocoder?? maybe archive this and suggest using geocoder and census_block_group images? instead?

also, how should we best go about informing users of available new versions if they have already used an older version?

**Comment by erikarasnick** [comment]
add more detailed usage instructions for mac, windows CMD prompt, and windows powershell

mac
`docker run --rm=TRUE -v "$PWD":/tmp degauss/geocoder my_address_file.csv`

windows cmd 
`docker run --rm=TRUE -v "%cd%":/tmp degauss/pepr_roadways:0.3 my_address_file_geocoded.csv`

windows powershell 
`docker run --rm=TRUE -v //c/Users/RASV5G/Desktop://tmp degauss/cchmc_batch_geocoder my_address_file_geocoded.csv`

(powershell may force user to expand path instead of using pwd, see here: https://stackoverflow.com/questions/50540721/docker-toolbox-error-response-from-daemon-invalid-mode-root-docker

**Comment by cole-brokamp** [comment]
make sure to look for addresses that are blank or all whitespace after we remove non-alphanumeric characters; this triggers an error when we `mappp` across all the addresses to geocode.
